import Layout from "@/components/Layout";
import Head from "next/head";
import Image from "next/image";
import AnimatedText from "@/components/AnimatedText";
import Link from "next/link";
import { LinkArrow } from "@/components/Icons";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="flex text-dark w-full min-h-screen dark:text-light">
        <Layout className="!px-32 !py-0">
          <div className="flex items-center justify-between w-full mt-28">
            <div className="w-1/3 ">
              <Image
                src="/images/gf_robot_welcome.png"
                alt="G-F brand robot welcoming blog readers"
                className=""
                width={0}
                height={0}
                sizes="100vw"
                style={{ width: "100%", height: "auto" }}
              />
            </div>
            <div className="w-3/5 flex flex-col items-center self-center">
              <AnimatedText
                text="Welcome to my Blog!"
                className="text-6xl !text-left "
              />
              <p className="my-4 lg:pr-24 text-lg font-medium ">
                Here, as a technology enthusiast with an insatiable thirst for
                knowledge, I share insights, discoveries, and reflections that
                capture the essence of my ongoing journey of learning.
              </p>
              {/* lg:self-center */}
              <div className="flex items-center self-start mt-2 ">
                <Link
                  href="/dummy.pdf"
                  target={"_blank"}
                  className="border-solid border-2 border-transparent hover:border-secondary flex items-center bg-secondary p-2.5 px-6 rounded-lg text-lg font-semibold hover:bg-light hover:text-secondary  text-light"
                  download={true}
                >
                  Articles <LinkArrow className={"w-6 ml-1"} />
                </Link>
                <Link
                  href="mailto:gabriel.fortia.pro@gmail.com"
                  target={"_blank"}
                  className="ml-4 text-lg font-medium capitalize text-dark underline dark:text-light"
                >
                  Contact
                </Link>
              </div>
            </div>
          </div>
        </Layout>
      </main>
    </>
  );
}
